language: ruby

before_install:
  - rvm 2.1.2

install:
  - bundle install

script:
  - jekyll build
  - check-links _site

after_success:
  - s3_website push --headless

env:
  global:
  - BUNDLE_ARCHIVE="caitlinphoto"
  - secure: WUtMInoqdxIr76dn/mlcAEQR1M86TYhWOUIJkr1uXKLJy/Dr+l9oruKGBQ6+CP4dlL7lZ8iQVkC/qRPis/3EwnSeBMVQwDPwcGi5Jaw4WYJFL9GVBt7qMGXDIZ7A3maS8iVRg8Gr+OJfKF/58Vxzv8aailnUmMLFgyR444O0egs=
  - secure: ULhrR+VBDRs7zK4dO8D3FXSVe7IY8GZUaW4vGW8C01eyjYOvPlV/tiaQKC8rGXvsN/LfPzzz6mOv+rWAAcOI9WoHufVjk+YM7d65s/6zTdWwD2T+XEeV8Tc4diaX9vdFPFDEm/KxpvWaVmcvIt4XxmRdijjj/69B8IJFMShG7F4=
  - secure: EKoKVSwoKVgYNtdvUWLEWDGghZZKNdqgzYNfiFh0R6JlY9+ggKZMvW/AP2YCTxD3E3Cgjc6d9/qlrHsDUdKS/xlKZ8wixkkxjb1K5Lhk8cUCaOZ5sSpiFj6nhN+OR/Qs5r18s+c2VSXfSgKfR9TdixpdqSzWz/jVHzbcTdv/MoY=
  - secure: V9Y8+cQBPgii/t2d5yQCd/k2Feq9AoiRrUFhx/HoJL+LCMxV0CjGtF5MQ9tS8gDgi/vlYFhsssmMEmpzX710WAsjpCZAxUZIEI1xkhwc2PHVOste7L1UGGvhdXdYAHa7UaEuKT7Tdg4Lcnkox/+T3o7uOcOpcCRacl/enSjjI3g=
  - secure: VGZ/7Ws9TXrznBIyIOQMJ9nrk7GacUGlTRpQUG/4yyPpexoqOtE3oiEWM00Ftu2az3Ng8tLLtd8705jeNALKIADofMRcR0ij2APVNwkdeMOBJaBkKGtf81Q1As3QFc4wPChFcfLGKezsrpFzwZT9c9WYzTr9d3HQ4tjW4C7FoSc=
  - secure: IhP1Qy+WHjaiMApO/OFTUHIpwhoiFLFVGDTx0VnqndMMBla56qRYgcMPxZZ7aqz8Negy4AVKAXzg5E1YJuz+QfDV0ehFH5PsqZeZvbKIxXEOnxKmLlLL5bUL37C9K3wGtgRdrZvsyZ2VmK/GX4+ualHkfqU2OoZhQ8n0W/YWBMg=