# Site settings
name: caitlinphoto.com
my_name: Caitlin McCarrick
title: Caitlin McCarrick
email: caitlin@caitlinphoto.com
description: "Photographer. Dog Lover. Santa Cruz."
baseurl: ""
url: "http://caitlinphoto.com"
blog_image_url: "/images/blog/"

me_image: "/images/caitlin-mccarrick.jpg"
about_me_image: "/images/caitlin-mccarrick-long.jpg"
full_me_image: "/images/caitlin-mccarrick-long.jpg"

cache:
  directories:
  - src/images/generated

# Build settings
markdown: kramdown
permalinks: pretty
source: src

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml


picture:
  source: images/originals
  output: images/generated
  markup: picturefill
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250